### PR TITLE
WIP: Add Gradle/Android support

### LINKED ISSUE #23: Gradle/Android issues
Hi! I was trying to setup your plugin to work with an Android project with Gradle. (I don't know gradle that well so bear with me) In the readme.md, I think this line is wrong:

```
ext.destFile = file("javaconfig.json")
        ext.config = [
            sourcePath: sourceSets.collect{ it.java.srcDirs }.flatten().collect{ relativePath(it) },
>>>            classPathFile: relativePath(tasks.getByPath(':vscodeClasspathFile').outputs.files.singleFile),
            outputDirectory: relativePath(new File(buildDir, 'vscode-classes'))
        ]
```

Upon removing `:` from the `:vsCodeClasspathFile` the gradle task finished successfully. If I leave it there:

```
$ ./gradlew vscode

FAILURE: Build failed with an exception.

* Where:
Build file '/home/nmilosev/Projects/android/alfaevid/android/app/build.gradle' line: 52

* What went wrong:
A problem occurred evaluating project ':app'.
> Task with path ':vscodeClasspathFile' not found in project ':app'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.628 secs
```

Also I think it's a good idea to specify in the readme where to put your tasks in an android project - it should be under `android { }`.

Also the `javaconfig.json` file is a bit wrong:

```
{
    "sourcePath": [
        "app/src/androidTest/java",
        "app/src/debug/java",
        "app/src/main/java",
        "app/src/release/java",
        "app/src/test/java",
        "app/src/testDebug/java",
        "app/src/testRelease/java"
    ],
    "classPathFile": "app/build/classpath.txt",
    "outputDirectory": "app/build/vscode-classes"
}
```

and it should be:

```
{
    "sourcePath": [
        "src/androidTest/java",
        "src/debug/java",
        "src/main/java",
        "src/release/java",
        "src/test/java",
        "src/testDebug/java",
        "src/testRelease/java"
    ],
    "classPathFile": "build/classpath.txt",
    "outputDirectory": "build/vscode-classes"
}
```

**When these little problems are fixed, the plugin works fantastically fast and well, dare I say faster than OmniSharp**

Thanks for the plugin, works great so far!

### PR DESCRIPTION
**Pull request by DonnieWest**
Almost certainly the wrong way to do this, but, it seems to currently add things to the classpath from Gradle/Android projects

I can't seem to get this to properly give me completions in a vanilla Android project, but I wonder if that's because I've ALSO hacked this to work on a VIM LSP project but it's equally likely I'm just doing something stupid here.

Feedback appreciated

Maybe fixes #23

### CODE REVIEW

**Comment by georgewfraser** [comment]
I am not a gradle expert, but you probably want to write a function that:
- Runs `gradle :dependencies` or `./gradlew :dependencies`
- Parses the output into a list of [Artifact](https://github.com/georgewfraser/vscode-javac/blob/master/src/main/java/org/javacs/Artifact.java)

Invoke that function from [here](https://github.com/georgewfraser/vscode-javac/blob/master/src/main/java/org/javacs/InferConfig.java#L327). There's already code that knows how to find gradle jars in `~/.gradle`

**Comment by DonnieWest** [comment]
The problems I'm running into with that method are:

1. With `gradle dependencies` you have to know the module name ahead of time that you want to call it on. ie Most Android projects start off with a root project and an app project. You would have to know ahead of time that the name of the module is app so you could invoke gradle with `gradle app:dependencies` 
2. It doesn't output ALL the needed dependencies. For instance, Android projects won't include the android.jar file

Even if we knew ahead of time what type of project it was, other calls such as `gradle androidDependencies` also suffer from the missing android.jar problem.

If it wasn't for that, turning Gradle's output into a list of Artifacts wouldn't be too hard at all. We just have to have a special case for AAR files that get decompressed into `~/.gradle/caches/transforms*` instead

**Comment by DonnieWest** [comment]
Any clue why it seems like I'm generating the correct classpath but not getting any real completions out of a stock Android Studio project?

I'll get some more time this week to track some of this down, just wondering if there's something I'm doing that obviously stupid here

**Comment by georgewfraser** [comment]
Can't you just do `gradle :dependencies` and get everything?

**Comment by georgewfraser** [comment]
Or maybe `gradle projects` and then several `gradle {project}:dependencies`

**Comment by DonnieWest** [comment]
I'd still miss out if dependencies like the android.jar file. It's not listed for some bizarre reason

**Comment by DonnieWest** [comment]
This doesn't seem feasible anymore - Android requires Java 8 to build and this project requires 10 to run. I'll reopen at a later time if it seems viable again

**Comment by GrimKriegor** [comment]
Hello there.

I am currently enjoying a quite comfy Android development setup with auto-completion and linting on Vim by using [vim-android](https://github.com/hsanson/vim-android.git) + [ALE](https://github.com/w0rp/ale) +  [java-language-server](https://github.com/georgewfraser/java-language-server) + [kotlin-language-server](https://github.com/fwcd/KotlinLanguageServer).

The creator of `vim-android`, hsanson, has been hard at work integrating Vim, ALE, javalsp and vim-android. The results are imo superb.

If like me you are eager to move the Android development workflow into Vim, give [that setup](https://github.com/hsanson/vim-android/blob/master/doc/vim-android.txt) a try.

I believe there are still some rough edges, especially in the Kotlin department, but for me its way better than using IntelliJ/Android Studio.

vim-android

**Comment by JartX** [comment]
> Hello there.
> 
> I am currently enjoying a quite comfy Android development setup with auto-completion and linting on Vim by using [vim-android](https://github.com/hsanson/vim-android.git) + [ALE](https://github.com/w0rp/ale) + [java-language-server](https://github.com/georgewfraser/java-language-server) + [kotlin-language-server](https://github.com/fwcd/KotlinLanguageServer).
> 
> The creator of `vim-android`, @hsanson, has been doing amazing work integrating Vim, ALE, javalsp and vim-android.
> 
> If like me, you are eager to move the Android development workflow into Vim, give [that setup](https://github.com/hsanson/vim-android/blob/master/doc/vim-android.txt) a try.
> 
> I believe there are still some rough edges, especially in the Kotlin department, but for me its better than using IntelliJ/Android Studio.
> 
> Thanks to everyone involved in making this a possibility.
> 
> Here are the relevant configuration bits from my dotfiles.
> 
> [~/.vimrc](https://github.com/GrimKriegor/dotfiles/blob/master/.vimrc)
> 
> ```
> let g:android_sdk_path = expand("$ANDROID_HOME")
> let g:gradle_loclist_show = 0
> let g:gradle_show_signs = 0
> ```
> 
> [~/.vim/after/ftplugin/java.vim](https://github.com/GrimKriegor/dotfiles/blob/master/.vim/after/ftplugin/java.vim)
> 
> ```
> let g:ale_linters = {'java': ['checkstyle', 'javalsp', 'android']}
> let g:ale_java_javalsp_executable = 'java-language-server'
> ```
> 
> [~/.vim/after/ftplugin/kotlin.vim](https://github.com/GrimKriegor/dotfiles/blob/master/.vim/after/ftplugin/kotlin.vim)
> 
> ```
> let g:ale_linters = {'kotlin': ['ktlint', 'languageserver', 'android']}
> let g:ale_kotlin_languageserver_executable = 'kotlin-language-server'
> ```
> 
> vim-android

I am trying to use it, but always says: symbols not found

**Pull request closed without merging**
