### PR TITLE
Add import on completion

### LINKED ISSUE #96: Add-import on completion
Right now, we automatically add imports on save: https://github.com/georgewfraser/java-language-server/blob/incremental/src/main/java/org/javacs/CompileBatch.java#L291

This works well for scenarios like copy-pasting large blocks of code, but it doesn't work great when you autocomplete:
- User starts typing the name of an unimported class
- User selects a particular unimported class and tab completes
- This class is still not imported, so subsequent autocomplete is broken until the user saves

For example, `new SomeNotImportedClass()._` will not autocomplete. 

The Language Server Protocol provides for this exact scenario with CompletionItem#additionalTextEdits: https://microsoft.github.io/language-server-protocol/specification#textDocument_completion

Related: #95, #44 

@albfan

### PR DESCRIPTION
**Pull request by rafaeldeoliveira**
idk if this is the best way to do it, but it works

add-imports

fixes #96

### CODE REVIEW

**Comment by ssilve1989** [comment]
@georgewfraser Any update on if this can be added? I am unable to get auto-import/complete working even on save/format with a Bazel project.

**Comment by georgewfraser** [comment]
Hey sorry for slow review. I'm supportive of this change, and I think it would be better to put "reorganize imports" behind a code-action once this is in. But I think this isn't quite the right way to do it, it crosses a lot of weird boundaries in how the methods are organized.

**Comment by rafaeldeoliveira** [comment]
Hi @georgewfraser, I think that in the next few weeks i'll be able to make a proper implementation, I'm closing this PR.

**Comment by albfan** [comment]
I tested this and just works. Has the benefit to use the selected class from dropdown so import will be correct in case of ambiguity.

@georgewfraser any suggestion on how to refactor this?

**Pull request closed without merging**
