### PR TITLE
Make javaLsFlag.txt and lib/src.zip optional

### PR DESCRIPTION
**Pull request by leighmcculloch**
What
===
Make javaLsFlag.txt and lib/src.zip optional.

Why
===
When using this tool standalone the lib/src.zip file doesn't seem to be
packaged inside what is jlinked and exceptions are raised because it
cannot be found. From the tests I've run it doesn't seem to make any
difference if the zip file is present or not, at least to the features I
am using. I don't really understand what the txt and zip file are for,
but it seems like this language server protocol can be used without
them.

### CODE REVIEW

**Comment by georgewfraser** [comment]
They're used to provide javadoc for the standard library. You are correct, they are not packaged inside what is jlinked. But I think javadocs are useful, it would be better if they get packaged for standalone usage.

**Comment by leighmcculloch** [comment]
Instead of packaging it in, how do you feel about making it something that's just looked up from `JAVA_HOME/lib/src.zip`? Most users who have a JDK installed will also have the src.zip file already on their computers. There are some exceptions, like OpenJDK where the src is a separate install on some distributions (e.g. Ubuntu, Debian), but it's a simple apt-get install for those people. This would also have the advantage of displaying the javadocs specifically provided with the version fo Java they are using.

Also, what's the licensing of the src.zip file? Is it MIT like the rest of the project, or does it have its own license?

**Comment by leighmcculloch** [comment]
Or specifying the location of src.zip manually as a command line option for standalone use?

**Comment by leighmcculloch** [comment]
I just gave a go of moving the `src.zip` into the `src/main/resources` folder and it works at being included in the jlink automatically and can easily be loaded in the code as a resource using the class loader. It simplifies the existing code a lot.

However, after doing that I took a look at the contents of the `src.zip` file and sampling a few Java files, they have an Oracle copyright at the top and no details permitting their use in any capacity. Is there a special license allowing their use and distribution in this project? If not, you could swap the `src.zip` out with the OpenJDK version, but even then its files are a modified GPLv2, and to my knowledge GPL is incompatible with the MIT license.

Given the licensing ambiguity I wouldn't be comfortable opening a PR moving the `src.zip` file to `src/main/resources` and perpetuating its use and distribution.

**Comment by leighmcculloch** [comment]
Alternative suggestion which is the implementation I'm using standalone at the moment: #82.

**Pull request closed without merging**
