### PR TITLE
Update link scripts so they can be run from Linux too

### PR DESCRIPTION
**Pull request by leighmcculloch**
### What
Update link scripts so they can be run from Linux too.

### Why
The location of java home is different on mac and debian, and on debian
there is no java_home executable to select version 11 of java. Given Java
can be installed in so many different ways on different operating systems
it is better that we just verify that the version of Java is being used that
we need and let the developer set it appropriately.

The patch script has been updated to use the JAVA_HOME path explicitly
for each command to ensure it uses the correct version of java when
multiple versions are installed, and when the user specifies java home.

### CODE REVIEW

**Comment by leighmcculloch** [comment]
I realize I've misinterpreted how the link scripts get used. They're both for use on Mac to build for Mac + Windows.

**Comment by georgewfraser** [comment]
What if instead we just delete `JAVA_HOME=...`, and throw an error if JAVA_HOME is absent or pointing to an old version of Java? 

It's kind of a weird think to try to figure out JAVA_HOME with a script, it's really something the user is supposed to do. I only set it up this way for my own convenience, because I use Java 8 for work but Java 11 for this project.

**Comment by leighmcculloch** [comment]
I think changing it to depend on the user is better for sure if you're comfortable with us going that route. I can update the scripts do to this and to display an error if the version of java is not `11`.

**Comment by leighmcculloch** [comment]
@georgewfraser I've pushed the changes to just check the version instead.

**Pull request merged**
