### PR TITLE
Multi moduling 

### PR DESCRIPTION
**Pull request by secondsun**
This change 
 * refactors the project into a generic LSP library and a Java Language Server implementation.  
 * updates the modules and packages to expose and open the LSP API
 * Updates test flavored things as appropriate to use the new module

I've been working on a parser for a personal project and wanted to add language server support.  You can see my WIP language server here if you want to see how this PR can be used in a unrelated project.  

https://github.com/secondsun/wla-language-server

### CODE REVIEW

**Comment by secondsun** [comment]
I understand it needs a rebase, and I will do so if you are interested in the PR.

**Comment by georgewfraser** [comment]
That's funny, I only added the lsp implementation a few days ago.

I'm happy to split this up so it can be re-used, but I'm wondering why you don't just use [lsp4j](https://github.com/eclipse/lsp4j)? Admittedly they went a little crazy with design-patterns, but it's a complete implementation of the protocol and they're doing a good job of keeping up with additions. The only reason I stopped using it is because I needed to be able to use jlink, and it was easier to just write my own LSP implementation than to try to modularize lsp4j.

**Comment by secondsun** [comment]
I saw this project first and the code was exactly what I needed.  LSP4j just looked like a lot more work to dive into.  Also I was going down the Java module path as well.

**Comment by secondsun** [comment]
Sounds good. I'll close this pr

**Pull request closed without merging**
