### PR TITLE
Allow for scoping the instance to a BUILD file

### PR DESCRIPTION
**Pull request by hkupty**
When working on a monorepo, it might be interesting to scope down the dependencies to just those of that particular subproject.

Now when starting the server on a subdirectory that contains a BUILD or has parent containing BUILD, it will scope down to that subproject.

This PR also comes with a change of behavior when compared to #160, which now dynamically selects the config provider based on whether the project is a bazel project or not. Ideally, this logic should be expanded so `InferConfig` is dropped entirely and individual implementations are split.

### CODE REVIEW

**Comment by georgewfraser** [comment]
I like this a lot:

> Now when starting the server on a subdirectory that contains a BUILD or has parent containing BUILD, it will scope down to that subproject.

I'm not a huge fan of the refactoring into `IConfig` though. Can we just do the behavior change, without changing the code structure?

**Comment by hkupty** [comment]
I built this on top of my previous PR, #160.
I guess it can be implemented directly in the `InferConfig` class, though.

It was just "accidental" that I did it on top of the previous one..

**Comment by georgewfraser** [comment]
Yeah I'd love to have the "open just one folder" feature, but I'm not super enthusiastic about the restructuring of the code.

**Comment by hkupty** [comment]
I'll follow up on this one once we decide how to go about with the previous (#160), but I'm leaning towards dropping everything. If you really feel like having 1-1 instance per BUILD file, I'll try to make that configurable. How does that sound?

**Pull request closed without merging**
